---
logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
        security: DEBUG

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://24efea61e3ad283784c8a0420b9ca651@o4506461207003136.ingest.sentry.io/4506461254189056
  traces-sample-rate: 1.0